/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetsRouteImport } from './routes/sets'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DataRouteImport } from './routes/data'
import { Route as CatsRouteImport } from './routes/cats'
import { Route as IndexRouteImport } from './routes/index'

const SetsRoute = SetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const CatsRoute = CatsRouteImport.update({
  id: '/cats',
  path: '/cats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cats': typeof CatsRoute
  '/data': typeof DataRoute
  '/import': typeof ImportRoute
  '/sets': typeof SetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cats': typeof CatsRoute
  '/data': typeof DataRoute
  '/import': typeof ImportRoute
  '/sets': typeof SetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cats': typeof CatsRoute
  '/data': typeof DataRoute
  '/import': typeof ImportRoute
  '/sets': typeof SetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cats' | '/data' | '/import' | '/sets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cats' | '/data' | '/import' | '/sets'
  id: '__root__' | '/' | '/cats' | '/data' | '/import' | '/sets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatsRoute: typeof CatsRoute
  DataRoute: typeof DataRoute
  ImportRoute: typeof ImportRoute
  SetsRoute: typeof SetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sets': {
      id: '/sets'
      path: '/sets'
      fullPath: '/sets'
      preLoaderRoute: typeof SetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cats': {
      id: '/cats'
      path: '/cats'
      fullPath: '/cats'
      preLoaderRoute: typeof CatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatsRoute: CatsRoute,
  DataRoute: DataRoute,
  ImportRoute: ImportRoute,
  SetsRoute: SetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
